on:
  push:
    branches:
      - main
name: Auto Release
jobs:
  build_and_release:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-gnu]
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-rust
        with:
          target: ${{ matrix.target }}
      - name: Create Artifact Archive
        id: create-archive
        uses: ./.github/actions/archive
        with:
          target: ${{ matrix.target }}
      # make pre-release for regular pushes
      - if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ${{ steps.create-artifact-archive.outputs.archive_name }}
            CHECKSUM
      # make a real release if there's a tag
      - if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Release ${{ github.ref_name }}"
          files: |
            ${{ steps.create-artifact-archive.outputs.archive_name }}
            CHECKSUM
